version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-local
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      # - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodbdata:/data/db
      # - mongoconfig:/data/configdb
volumes:
  mongodbdata: